// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9OilU3PVAXjIeRDNB3cv0ArcWL6TzMs',
    appId: '1:253862892684:web:e4a26b14c312400c1b97a9',
    messagingSenderId: '253862892684',
    projectId: 'rpe-tracker-589bb',
    authDomain: 'rpe-tracker-589bb.firebaseapp.com',
    storageBucket: 'rpe-tracker-589bb.appspot.com',
    measurementId: 'G-227P4QK80M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuo393PuxKdZnpifqywvVmEP8yOdMFnhU',
    appId: '1:253862892684:android:d71788eae72042661b97a9',
    messagingSenderId: '253862892684',
    projectId: 'rpe-tracker-589bb',
    storageBucket: 'rpe-tracker-589bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6eqDblfVItMqLu5WOlHaTxLyU4NDf-g',
    appId: '1:253862892684:ios:61571b9e417cbbd51b97a9',
    messagingSenderId: '253862892684',
    projectId: 'rpe-tracker-589bb',
    storageBucket: 'rpe-tracker-589bb.appspot.com',
    iosBundleId: 'com.example.rpeStrength',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6eqDblfVItMqLu5WOlHaTxLyU4NDf-g',
    appId: '1:253862892684:ios:61571b9e417cbbd51b97a9',
    messagingSenderId: '253862892684',
    projectId: 'rpe-tracker-589bb',
    storageBucket: 'rpe-tracker-589bb.appspot.com',
    iosBundleId: 'com.example.rpeStrength',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9OilU3PVAXjIeRDNB3cv0ArcWL6TzMs',
    appId: '1:253862892684:web:2cd237ea1118ef091b97a9',
    messagingSenderId: '253862892684',
    projectId: 'rpe-tracker-589bb',
    authDomain: 'rpe-tracker-589bb.firebaseapp.com',
    storageBucket: 'rpe-tracker-589bb.appspot.com',
    measurementId: 'G-KJ9SH97PB0',
  );
}
